const siteTitle = 'wasted\npotential';
const anagrams = [
    'wasted\npotential',
    'wasted\npotential',
    'wasted\npotential',
    'wasted\npotential',
    'wasted\npotential',
    'wasted\npotential',
    'salted\nnewt\npatio',
    'wipe\ndental\nstoat',
    'wean\nspittle\ntoad',
    'slow\ntainted\npeat',
    'weed at\nlost paint',
    'tepid snot\ntea law',
]

const letterHeight = 50; // all letters must be same height
const assetFolder = 'assets/';
const letters = [
    {
        char: 'w',
        id: 'w1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'w1.png',
        sprite: null,
    },
    {
        char: 'a',
        id: 'a1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'a1.png',
        sprite: null,
    },
    {
        char: 's',
        id: 's1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 's1.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 't1.png',
        sprite: null,
    },
    {
        char: 'e',
        id: 'e1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'e1.png',
        sprite: null,
    },
    {
        char: 'd',
        id: 'd1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'd1.png',
        sprite: null,
    },
    {
        char: 'p',
        id: 'p1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'p1.png',
        sprite: null,
    },
    {
        char: 'o',
        id: 'o1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'o1.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't2',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 't2.png',
        sprite: null,
    },
    {
        char: 'e',
        id: 'e2',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'e2.png',
        sprite: null,
    },
    {
        char: 'n',
        id: 'n1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'n1.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't3',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 't3.png',
        sprite: null,
    },
    {
        char: 'i',
        id: 'i1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'i1.png',
        sprite: null,
    },
    {
        char: 'a',
        id: 'a2',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'a2.png',
        sprite: null,
    },
    {
        char: 'l',
        id: 'l1',
        used: false,
        destX: 0,
        destY: 0,
        w: 50,
        img: 'l1.png',
        sprite: null,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
];
