const siteTitle = 'wasted\npotential';
const anagrams = [
    'salted\nnewt\npatio',
    'wipe\ndental\nstoat',
    'wean\nspittle\ntoad',
    'slow\ntainted\npeat',
    'weed at\nlost paint',
    'tepid snot\ntea law',
]

const letterHeight = 60; // all letters must be same height
const assetFolder = 'assets/';
const letters = [
    {
        char: 'w',
        id: 'w1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'w1_01.png',
        sprite: null,
    },
    {
        char: 'a',
        id: 'a1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'a1_01.png',
        sprite: null,
    },
    {
        char: 's',
        id: 's1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 's1_01.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 't1_01.png',
        sprite: null,
    },
    {
        char: 'e',
        id: 'e1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'e1_01.png',
        sprite: null,
    },
    {
        char: 'd',
        id: 'd1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'd1_01.png',
        sprite: null,
    },
    {
        char: 'p',
        id: 'p1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'p1_01.png',
        sprite: null,
    },
    {
        char: 'o',
        id: 'o1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'o1_01.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't2',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 't2_01.png',
        sprite: null,
    },
    {
        char: 'e',
        id: 'e2',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'e2_01.png',
        sprite: null,
    },
    {
        char: 'n',
        id: 'n1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'n1_01.png',
        sprite: null,
    },
    {
        char: 't',
        id: 't3',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 't3_01.png',
        sprite: null,
    },
    {
        char: 'i',
        id: 'i1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'i1_01.png',
        sprite: null,
    },
    {
        char: 'a',
        id: 'a2',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'a2_01.png',
        sprite: null,
    },
    {
        char: 'l',
        id: 'l1',
        used: false,
        destX: 0,
        destY: 0,
        w: 38,
        img: 'l1_01.png',
        sprite: null,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
    {
        char: ' ',
        used: false,
        destX: 0,
        destY: 0,
        w: 35,
    },
];
