const letters = [
    {
        char: 'w',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/w1.png',
    },
    {
        char: 'a',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/a1.png',
    },
    {
        char: 's',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/s1.png',
    },
    {
        char: 't',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/t1.png',
    },
    {
        char: 'e',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/e1.png',
    },
    {
        char: 'd',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/d1.png',
    },
    {
        char: 'p',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/p1.png',
    },
    {
        char: 'o',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/o1.png',
    },
    {
        char: 't',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/t2.png',
    },
    {
        char: 'e',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/e2.png',
    },
    {
        char: 'n',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/n1.png',
    },
    {
        char: 't',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/t3.png',
    },
    {
        char: 'i',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/i1.png',
    },
    {
        char: 'a',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/a2.png',
    },
    {
        char: 'l',
        destX: 0,
        destY: 0,
        h: 50,
        w: 50,
        img: 'assets/l1.png',
    },
];
