export const letterHeight = 60; // all letters must be same height
export const letterSpacing = 20;
export const spritesheetLocation = '__ROOT_URL__assets/1x/packed.json';
export const minStageWidth = 11 * 34 + 12 * letterSpacing;

export const siteTitle = 'wasted\npotential';
export const anagrams = [
	'salted\nnewt\npatio',
	'stoat\ndental\nwipe',
	'wean\nspittle\ntoad',
	'slow\ntainted\npeat',
	'weed at\nlost paint',
	'tepid snot\ntea law',
	'weep on\nstilt data',
	'ape lad\ntone twist',
	'tie down\nsalt pate',
	'a pitted\nteal snow',
	'saline\nwatt\ndepot',
	'tweet aid\nnot slap',
	'sand wit\ntotal pee',
	'potent\nlead\nwaist',
	'tasted\npiano\nwelt',
	'sat on\nwetted\npail',
	'nap tide\ntote slaw',
	'want\ntoiled\npaste',
	'total\npained\nstew',
	'tan wet\nspot ailed',
	'a not\npleased\ntwit',
	'swat a\npolite\ndent',
	'patented\ntoil saw',
	'patted\nwaste\nloin',
	'owe\ntainted\nsplat',
	'toiled\npant waste',
	'tot ate\nwaned lisp',
	'toe tap\nwas linted',
	'wasp on\nlatte diet',
	'notate\ntilde\nswap',
	'stoned at\ntile paw',
	'palest\ntow tan die',
];

export const letters = [
	{
		char: 'w',
		id: 'w1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['w1_01.png', 'w1_02.png', 'w1_03.png', 'w1_04.png'],
		sprite: null,
	},
	{
		char: 'a',
		id: 'a1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['a1_01.png', 'a1_02.png', 'a1_03.png', 'a1_04.png'],
		sprite: null,
	},
	{
		char: 's',
		id: 's1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['s1_01.png', 's1_02.png', 's1_03.png', 's1_04.png'],
		sprite: null,
	},
	{
		char: 't',
		id: 't1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['t1_01.png', 't1_02.png', 't1_03.png', 't1_04.png'],
		sprite: null,
	},
	{
		char: 'e',
		id: 'e1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['e1_01.png', 'e1_02.png', 'e1_03.png', 'e1_04.png'],
		sprite: null,
	},
	{
		char: 'd',
		id: 'd1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['d1_01.png', 'd1_02.png', 'd1_03.png', 'd1_04.png'],
		sprite: null,
	},
	{
		char: 'p',
		id: 'p1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['p1_01.png', 'p1_02.png', 'p1_03.png', 'p1_04.png'],
		sprite: null,
	},
	{
		char: 'o',
		id: 'o1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['o1_01.png', 'o1_02.png', 'o1_03.png', 'o1_04.png'],
		sprite: null,
	},
	{
		char: 't',
		id: 't2',
		used: false,
		destX: 0,
		destY: 0,
		img: ['t2_01.png', 't2_02.png', 't2_03.png', 't2_04.png'],
		sprite: null,
	},
	{
		char: 'e',
		id: 'e2',
		used: false,
		destX: 0,
		destY: 0,
		img: ['e2_01.png', 'e2_02.png', 'e2_03.png', 'e2_04.png'],
		sprite: null,
	},
	{
		char: 'n',
		id: 'n1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['n1_01.png', 'n1_02.png', 'n1_03.png', 'n1_04.png'],
		sprite: null,
	},
	{
		char: 't',
		id: 't3',
		used: false,
		destX: 0,
		destY: 0,
		img: ['t3_01.png', 't3_02.png', 't3_03.png', 't3_04.png'],
		sprite: null,
	},
	{
		char: 'i',
		id: 'i1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['i1_01.png', 'i1_02.png', 'i1_03.png', 'i1_04.png'],
		sprite: null,
	},
	{
		char: 'a',
		id: 'a2',
		used: false,
		destX: 0,
		destY: 0,
		img: ['a2_01.png', 'a2_02.png', 'a2_03.png', 'a2_04.png'],
		sprite: null,
	},
	{
		char: 'l',
		id: 'l1',
		used: false,
		destX: 0,
		destY: 0,
		img: ['l1_01.png', 'l1_02.png', 'l1_03.png', 'l1_04.png'],
		sprite: null,
	},
	{
		char: ' ',
		used: false,
		destX: 0,
		destY: 0,
		w: 34,
	},
	{
		char: ' ',
		used: false,
		destX: 0,
		destY: 0,
		w: 34,
	},
	{
		char: ' ',
		used: false,
		destX: 0,
		destY: 0,
		w: 34,
	},
	{
		char: ' ',
		used: false,
		destX: 0,
		destY: 0,
		w: 34,
	},
];
